on: [push]

name: Linux_Container_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Azure login
      uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}
          
    - uses: azure/docker-login@v1
      with:
        login-server: imagestoring.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t imagestoring.azurecr.io/nodejssampleapp:${{ github.sha }}
        docker push imagestoring.azurecr.io/nodejssampleapp:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'nodeapp-deploy'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: 'imagestoring.azurecr.io/nodejssampleapp:${{ github.sha }}'
